<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SampleRestAPI</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>25514006-9a3d-45a1-a94a-d107414512e2</testSuiteGuid>
   <testCaseLink>
      <guid>82b398fc-c02e-4c42-a160-b58e54ed77ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SampleRestAPI_TC/01_GetUserDetails/01_SingleUserDetails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a142eae4-1477-412d-8d61-37afa1ef9be6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce7e6b58-8415-4a6b-856f-40f0dadcc9f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf9dbef9-9f14-444d-96d8-88456127b4f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a4d7dce-21f9-4b0e-bf35-e3abe0fc1916</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SampleRestAPI_TC/01_GetUserDetails/02_ListUserDetails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46ecb953-02a1-49d1-931e-cdeb68da7cbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0678ab8-2dd7-43ad-8608-e35db465e415</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b0e3b8-3196-408c-ab12-6459833c4c84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d84dd81-57b0-413a-86cd-26e217919463</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SampleRestAPI_TC/02_CreateUserDetails/03_CreateUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>246a59a4-48f2-49cf-ba76-2e10767ec58e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0279a1-8df7-41ac-84de-e136a9d658ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>968ab496-d1a8-42a7-a818-f1f920c961a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>645d292f-51f1-4862-b651-6e941fcbda4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SampleRestAPI_TC/02_CreateUserDetails/04_CreateRegister</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>567cb5a8-ef7c-4666-80e6-fd31f1c71b35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1c24a7d-1fb8-4206-bbed-cd0adb235b5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SampleRestAPI_TC/02_CreateUserDetails/05_CreateMultipleUsers</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cd343628-b4e8-4628-beff-0da46d632fe7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cd343628-b4e8-4628-beff-0da46d632fe7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>ba4c6643-e04b-4116-84d6-e9f4a67996af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd343628-b4e8-4628-beff-0da46d632fe7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Job</value>
         <variableId>c4ddc303-4e46-4231-bffc-5cbe87bff534</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0f05b8f-f481-43a9-9108-b81ff87e9ceb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65fc1da6-18c4-4ccc-9d71-99ce374c2f16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SampleRestAPI_TC/03_UpdateUserDetails/06_UpdateUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b608ab-ade9-45db-895a-3afdec7fb79a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd4d1763-1c7e-4a40-8ece-e058e50969db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61c71253-7023-445c-8eef-0e9948290af7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SampleRestAPI_TC/03_UpdateUserDetails/07_UpdateUser_APIChaining</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27ad6b66-dbe2-4584-a899-40aad03ae8af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8b2228c-eb40-4176-8c47-6d691bec494d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2df49f5f-cf8b-4d95-ae04-a2c39eebe56a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SampleRestAPI_TC/04_DeleteUser/08_ValidateDeleteUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35af7ae8-5cca-4f43-a8be-76178a43fd4e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
